### ISSUE TITLE
Region can not be specify as a command argument

### ISSUE THREAD

**Issue by jamengual** [ken-tune/cloud-watch-for-marklogic#1]
Hi.

I realize after a while that the SNS topic and cloudwatch alerts were setup in the wrong region.

maybe the tool should look at the instance role/region to set them in the same region or have a command line argument for that.

even passing the AWS_DEFAULT_REGION still set the sns topics in us-east-1.

Thanks.

**Comment by jamengual** [comment]
Also cnc is a global variable to set the cloudwatch boto connection but SNS is not coded the same way so maybe having a global variable to set connections to both could help to be able to set the connection using another region like 

cwc = boto.ec2.cloudwatch.connect_to_region('us-west-2')
sns = boto.sns.connect_to_region('us-west-2')

for example.

**Comment by mustard57** [comment]
Hi Pepe

Thanks for your mail.

Good point. I hadn't picked up that the connection objects default to
us-east-1 ( as I was working in us-east-1 ).

Looks like your patch will work - but I'll probably put in something that
uses the region of the machine

my_session = boto3.session.Session()
my_region = my_session.region_name

( see http://stackoverflow.com/questions/37514810/how-to-get-the-region-of-the-current-user-from-boto
)

Looks like your patch will work - but I'll probably put in something that
uses the region of the machine - just to minimize the config, or maybe that
as the default with the ability to over-ride in config.py.

Re SNSConnection - this is only needed when setting up alarms - so I made
it a local just to avoid the overhead of having it initialized whenever
--storeMetrics is run, as it isn't needed. There's probably not that much
overhead, but that felt like a good decision.

I kind of have plans for the weekend but I should definitely be able to
patch in something like the above during the week next week.

Regards

Ken Tune

**Comment by ken-tune** [comment]
Hi Pepe

Addressed.

Thanks

Ken Tune
