### ISSUE TITLE
What if Metric and Key are not in {Unit:Value} format

### ISSUE THREAD

**Issue by rtirak** [ken-tune/cloud-watch-for-marklogic#6]
What if we want to pull information like os-version from /manage/v2/hosts/$OBJECT_ID$?view=status

You will see on that page the os-version "key" is in this format os-version: Linux 64bit Red Hat etc. Not the {key:value} format

Does the code have a use case for a metric like that, or could a use case like this be added?

Here would be my xml in the metrics.xml file for os-version:
``
<metric type="Hosts">
    <service_description>os-version</service_description>
    <service_note>Host OS Version</service_note>
    <path>/manage/v2/hosts/$OBJECT_ID$?view=status</path>
    <key>$SERVICE_DESCRIPTION$</key>
    <thresholds>
        
        <threshold>
          <type>critical</type>
          <comparison-operator>lt</comparison-operator>
          <value>1</value>
        </threshold>
    </thresholds>                    
  </metric>
``

**Comment by tgh192** [comment]
I also have a similar use case and would be very interested in learning if this is possible.

**Comment by ken-tune** [comment]
HI @rtirak 

Thanks for your interest. I left MarkLogic in June 2018 so no longer maintain this repository. You are welcome to fork it or submit a pull request. Suggest you take a look at the code and see if you're able to answer your question yourself - I don't really have the spare time to dig in unfortunately.

I'm sure the answer is yes you can though - likely it's just a simple matter of programming :-)
Ken Tune

**Comment by rtirak** [comment]
@ken-tune 

Sounds good sir. Me and a few others have started to take a look, and we agree should just be a matter of adding the case into the code. I appreciate your work!

Thanks,
